version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-backend"
s3_bucket = "resume-backend-niclaszll"
s3_prefix = "aws-sam"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
